---
- name: "'{{ item }}' - Select params from configs"
  set_fact:
    params: '{{ geokrety_environments | selectattr("name", "equalto", item) | list | first }}'

- name: "'{{ item }}' Define instance base directory"
  set_fact:
    geokrety_base_dir: "{{ geokrety_home }}/instances/{{ item }}"

- debug:
    msg: "Base directory for instance '{{ item }}' is {{ geokrety_base_dir }}"

- name: "'{{ item }}' Prepare environment"
  include_tasks: 10-prepare-environment.yml

- name: "'{{ item }}' Clone git repositories"
  include_tasks: 20-clone-git.yml

- name: "'{{ item }}' Mount CDN directories over AUFS"
  include_tasks: 25-aufs.yml
  when: "item != 'prod' and (params.new_env_flag is not defined or not params.new_env_flag)"

- name: "'{{ item }}' Build images"
  include_tasks: 30-build-images.yml

- block:
    - name: "'{{ item }}' Clone git repositories for monitoring"
      include_tasks: 21-clone-git-monitoring.yml
    - name: "'{{ item }}' Build images for monitoring"
      include_tasks: 31-build-images-monitoring.yml
  when: "params.monitoring is defined"

- block:
    - name: "'{{ item }}' Clone git repositories for pictures processor"
      include_tasks: 22-clone-git-pictures-processor.yml
    - name: "'{{ item }}' Build images for pictures processor"
      include_tasks: 32-build-images-pictures-processor.yml
  when: "params.pictures_processor is defined"

- block:
    - name: "'{{ item }}' Clone git repositories for postgres"
      include_tasks: 23-clone-git-postgres.yml
    - name: "'{{ item }}' Build images for postgres"
      include_tasks: 33-build-images-postgres.yml
  when: "params.postgres is defined"

- block:
    - name: "'{{ item }}' Clone git repositories for SVG2PNG"
      include_tasks: 24-clone-git-svg-to-png.yml
    - name: "'{{ item }}' Build images for SVG2PNG"
      include_tasks: 34-build-images-svg-to-png.yml
  when: "params.svg_to_png is defined"

- block:
    - name: "'{{ item }}' Clone git repositories for bootstrap-email"
      include_tasks: 24-clone-git-bootstrap-email.yml
    - name: "'{{ item }}' Build images for bootstrap-email"
      include_tasks: 34-build-images-bootstrap-email.yml
  when: "params.bootstrap_email is defined"

- block:
    - name: "'{{ item }}' Clone git repositories for osm-static-maps"
      include_tasks: 24-clone-git-osm-static-maps.yml
    - name: "'{{ item }}' Build images for osm-static-maps"
      include_tasks: 34-build-images-osm-static-maps.yml
  when: "params.osm_static_maps is defined"

- block:
    - name: "'{{ item }}' Process accounts cleaner image"
      include_tasks: 35-build-images-accounts-cleaner.yml
  when: "params.accounts_cleaner is defined"

- block:
    - name: "'{{ item }}' Process accounts cleaner image"
      include_tasks: 36-build-images-basex-amqp-sync.yml
  when: "params.basex_amqp_sync is defined"

- name: "'{{ item }}' Deploy stack"
  include_tasks: 40-deploy-images.yml
