---

- name: "'{{ item }}' - Create base directory"
  file:
    path: "{{ geokrety_base_dir }}"
    state: directory
    owner: "{{ geokrety_username }}"
    group: "{{ geokrety_group }}"
    mode: 0750

- name: "'{{ item }}' - Create srtm directory"
  file:
    path: "{{ geokrety_home }}/databases/srtm"
    state: directory
    owner: "{{ geokrety_username }}"
    group: "{{ geokrety_group }}"
    mode: 0755

- name: "'{{ item }}' - Create mysql directory"
  file:
    path: "{{ geokrety_base_dir }}/mysql"
    state: directory
    owner: "999"
    group: "0"
    mode: 0750

- name: "'{{ item }}' - Create postgres directory"
  file:
    path: "{{ geokrety_base_dir }}/BaseXData"
    state: directory
    owner: "1000"
    group: "1000"
    mode: 0775
  when: params.basex is defined and params.basex.host is defined

- name: "'{{ item }}' - Create rabbitmq directory"
  file:
    path: "{{ geokrety_base_dir }}/rabbitmq"
    state: directory
    owner: "1000"
    group: "1000"
    mode: 0775
  when: params.rabbitmq is defined and params.rabbitmq.host is defined

- name: "'{{ item }}' - Create postgres directory"
  file:
    path: "{{ geokrety_base_dir }}/postgres"
    state: directory
    owner: "999"
    group: "0"
    mode: 0750

- name: "'{{ item }}' - Create minio directory"
  file:
    path: "{{ geokrety_base_dir }}/minio"
    state: directory
    mode: 0770
  when: "params.minio is defined"

- name: "'{{ item }}' - Create prometheus directory"
  file:
    path: "{{ geokrety_base_dir }}/prometheus"
    state: directory
    owner: "65534"
    group: "65534"
    mode: 0770
  when: "params.monitoring is defined"

- name: "'{{ item }}' - Create grafana directory"
  file:
    path: "{{ geokrety_base_dir }}/grafana"
    state: directory
    owner: "472"
    group: "472"
    mode: 0770
  when: "params.monitoring is defined"

- name: "'{{ item }}' - Create assets directory"
  file:
    path: "{{ geokrety_base_dir }}/data/assets"
    state: directory
    owner: "33"
    group: "33"
    mode: 0775

- name: "'{{ item }}' - Create cdn PROD directory"
  file:
    path: "{{ geokrety_home }}/instances/prod/data/cdn"
    state: directory
    owner: "www-data"
    group: "{{ geokrety_group }}"
    mode: 0750

- name: "'{{ item }}' - Create dbdump PROD directory"
  file:
    path: "{{ geokrety_home }}/instances/prod/dbdump"
    state: directory
    owner: "{{ geokrety_username }}"
    group: "{{ geokrety_group }}"
    mode: 0750

- name: "'{{ item }}' - Create 'msmtp.conf'"
  template:
    src: configs/msmtprc
    dest: "{{ geokrety_base_dir }}/msmtprc"
    owner: root
    group: root
    mode: 0644

## Obsolete in Debian Buster
- name: "'{{ item }}' - Create 'ssmtp.conf'"
  template:
    src: configs/ssmtp.conf
    dest: "{{ geokrety_base_dir }}/ssmtp.conf"
    owner: root
    group: root
    mode: 0644
