---

- name: "'{{ item }}' - Create base directory"
  file:
    path: "{{ geokrety_base_dir }}"
    state: directory
    owner: "{{ geokrety_username }}"
    group: "{{ geokrety_group }}"
    mode: 0750

- name: "'{{ item }}' - Create mysql directory"
  file:
    path: "{{ geokrety_base_dir }}/mysql"
    state: directory
    owner: "999"
    group: "0"
    mode: 0750

- name: "'{{ item }}' - Create minio directory"
  file:
    path: "{{ geokrety_base_dir }}/minio"
    state: directory
    mode: 0770
  when: "params.minio is defined"

- name: "'{{ item }}' - Create prometheus directory"
  file:
    path: "{{ geokrety_base_dir }}/prometheus"
    state: directory
    owner: "65534"
    group: "65534"
    mode: 0770
  when: "params.monitoring is defined"

- name: "'{{ item }}' - Create grafana directory"
  file:
    path: "{{ geokrety_base_dir }}/grafana"
    state: directory
    owner: "472"
    group: "472"
    mode: 0770
  when: "params.monitoring is defined"

- name: "'{{ item }}' - Create cdn PROD directory"
  file:
    path: "{{ geokrety_home }}/instances/prod/data/cdn"
    state: directory
    owner: "www-data"
    group: "{{ geokrety_group }}"
    mode: 0750

- name: "'{{ item }}' - Create dbdump PROD directory"
  file:
    path: "{{ geokrety_home }}/instances/prod/dbdump"
    state: directory
    owner: "{{ geokrety_username }}"
    group: "{{ geokrety_group }}"
    mode: 0750

- name: "'{{ item }}' - Create 'ssmtp.conf'"
  template:
    src: configs/ssmtp.conf
    dest: "{{ geokrety_base_dir }}/ssmtp.conf"
    owner: root
    group: root
    mode: 0644
