---

- name: "'{{ item }}' Define CDN image name"
  set_fact:
    geokrety_docker_image_cdn_image_name: "{{ ('local/' if params.cdn.localdir is defined else '') + geokrety_docker_image_cdn_image }}"

- name: "'{{ item }}' Define NGINX image name"
  set_fact:
    geokrety_docker_image_nginx_image_name: "{{ ('local/' if params.nginx.localdir is defined else '') + geokrety_docker_image_nginx_image }}"

# Image name changed between GKv1 and GKv2
- block:
  - name: "'{{ item }}' Define BASE image name"
    set_fact:
      geokrety_docker_image_website_base_image_name: "{{ ('local/' if params.base.localdir is defined  else '') + params.base.image_name }}"
    when: params.base.image_name is defined

  - name: "'{{ item }}' Define BASE image name"
    set_fact:
      geokrety_docker_image_website_base_image_name: "{{ ('local/' if params.base.localdir is defined  else '') + geokrety_docker_image_website_base_image }}"
    when: params.base.image_name is not defined

  - name: "'{{ item }}' Define WEBSITE image name"
    set_fact:
      geokrety_docker_image_website_image_name: "{{ ('local/' if params.website.localdir is defined  else '') + params.website.image_name }}"
    when: params.website.image_name is defined

  - name: "'{{ item }}' Define WEBSITE image name"
    set_fact:
      geokrety_docker_image_website_image_name: "{{ ('local/' if params.website.localdir is defined  else '') + geokrety_docker_image_website_image }}"
    when: params.website.image_name is not defined

  - name: "'{{ item }}' Define CRON image name"
    set_fact:
      geokrety_docker_image_cron_image_name: "{{ ('local/' if params.cron.localdir is defined  else '') + params.cron.image_name }}"
    when: params.cron.image_name is defined

  - name: "'{{ item }}' Define CRON image name"
    set_fact:
      geokrety_docker_image_cron_image_name: "{{ ('local/' if params.cron.localdir is defined  else '') + geokrety_docker_image_cron_image }}"
    when: params.cron.image_name is not defined


- name: "'{{ item }}' Define CDN image tag"
  set_fact:
    geokrety_docker_image_cdn_image_tag: "{{ 'devel' if params.cdn.localdir is defined else (params.cdn.docker_tag | default(geokrety_cdn_image.docker_tag) | replace('/','-')) }}"

- name: "'{{ item }}' Define NGINX image tag"
  set_fact:
    geokrety_docker_image_nginx_image_tag: "{{ 'devel' if params.nginx.localdir is defined else (params.nginx.docker_tag | default(geokrety_nginx_image.docker_tag) | replace('/','-')) }}"

- name: "'{{ item }}' Define BASE image tag"
  set_fact:
    geokrety_docker_image_website_base_image_tag: "{{ 'devel' if params.base.localdir is defined else (params.base.docker_tag | default(geokrety_base_image.docker_tag) | replace('/','-')) }}"

- name: "'{{ item }}' Define WEBSITE image tag"
  set_fact:
    geokrety_docker_image_website_image_tag: "{{ 'devel' if params.website.localdir is defined else (params.website.docker_tag | default(geokrety_website_image.docker_tag) | replace('/','-')) }}"

- name: "'{{ item }}' Define CRON image tag"
  set_fact:
    geokrety_docker_image_cron_image_tag: "{{ 'devel' if params.cron.localdir is defined else (params.cron.docker_tag | default(geokrety_cron_image.docker_tag) | replace('/','-')) }}"


- name: "'{{ item }}' - Build CDN image - {{ params.cdn.localdir }} | {{ geokrety_docker_image_cdn_image_name }}:{{ geokrety_docker_image_cdn_image_tag }}"
  docker_image:
    name: "{{ geokrety_docker_image_cdn_image_name }}:{{ geokrety_docker_image_cdn_image_tag }}"
    source: build
    force_source: yes
    push: no
    build:
      path: "{{ params.cdn.localdir }}"
      pull: yes
  when: params.cdn.localdir is defined

- name: "'{{ item }}' - Build NGINX image - {{ params.nginx.localdir }} | {{ geokrety_docker_image_nginx_image_name }}:{{ geokrety_docker_image_nginx_image_tag }}"
  docker_image:
    name: "{{ geokrety_docker_image_nginx_image_name }}:{{ geokrety_docker_image_nginx_image_tag }}"
    source: build
    force_source: yes
    push: no
    build:
      path: "{{ params.nginx.localdir }}"
      pull: yes
  when: params.nginx.localdir is defined

- name: "'{{ item }}' - Build BASE image - {{ params.base.localdir | default(geokrety_base_dir+'/git/base') }} | {{ geokrety_docker_image_website_base_image_name }}:{{ geokrety_docker_image_website_base_image_tag }}"
  docker_image:
    name: "{{ geokrety_docker_image_website_base_image_name }}:{{ geokrety_docker_image_website_base_image_tag }}"
    source: build
    force_source: yes
    push: no
    build:
      path: "{{ params.base.localdir }}"
      pull: yes
  when: params.base.localdir is defined

- block:
    - name: "'{{ item }}' - Build BASE image get git describe - {{ params.website.localdir }}"
      shell: "git describe --tags"
      args:
        chdir: "{{ params.website.localdir }}"
      register: geokrety_website_latest_tag

    - name: "'{{ item }}' - Build WEBSITE image - {{ params.website.localdir }} | {{ geokrety_docker_image_website_image_name }}:{{ geokrety_docker_image_website_image_tag }} | base:{{ geokrety_docker_image_website_base_image_name }}:{{ geokrety_docker_image_website_base_image_tag }}"
      docker_image:
        name: "{{ geokrety_docker_image_website_image_name }}:{{ geokrety_docker_image_website_image_tag }}"
        source: build
        force_source: yes
        push: no
        build:
          path: "{{ params.website.localdir }}"
          pull: "{{ params.base.localdir is not defined }}"
          args:
            BASE_IMAGE: "{{ geokrety_docker_image_website_base_image_name }}"
            BASE_TAG: "{{ geokrety_docker_image_website_base_image_tag }}"
            GIT_COMMIT: "{{ geokrety_website_latest_tag.stdout }}"
  when: params.website.localdir is defined

- name: "'{{ item }}' - Build CRON image - {{ params.cron.localdir }} | {{ geokrety_docker_image_cron_image_name }}:{{ geokrety_docker_image_cron_image_tag }}"
  docker_image:
    name: "{{ geokrety_docker_image_cron_image_name }}:{{ geokrety_docker_image_cron_image_tag }}"
    source: build
    force_source: yes
    push: no
    build:
      path: "{{ params.cron.localdir }}"
      pull: yes
      args:
        IMAGE: "{{ geokrety_docker_image_website_image_name }}:{{ geokrety_docker_image_website_base_image_tag }}"
  when: params.cron.localdir is defined
