---

- name: "'{{ item }}' Define PICTURES PROCESSOR BASE image name"
  set_fact:
    geokrety_docker_image_pictures_processor_base_image_name: "{{ ('' if geokrety_push_images else 'local/') + geokrety_docker_image_pictures_processor_base_image_name }}"

- name: "'{{ item }}' Define PICTURES PROCESSOR DOWNLOADER image name"
  set_fact:
    geokrety_docker_image_pictures_processor_downloader_image_name: "{{ ('' if geokrety_push_images else 'local/') + geokrety_docker_image_pictures_processor_downloader_image_name }}"

- name: "'{{ item }}' Define PICTURES PROCESSOR UPLOADER image name"
  set_fact:
    geokrety_docker_image_pictures_processor_uploader_image_name: "{{ ('' if geokrety_push_images else 'local/') + geokrety_docker_image_pictures_processor_uploader_image_name }}"

- name: "'{{ item }}' - Build and push PICTURES PROCESSOR BASE image - {{ params.pictures_processor.localdir | default(geokrety_base_dir+'/git/pictures-processor') }} | {{ geokrety_docker_image_pictures_processor_base_image_name }}:{{ item }}"
  docker_image:
    name: "{{ geokrety_docker_image_pictures_processor_base_image_name }}:{{ item }}"
    source: build
    force_source: yes
    push: "{{ geokrety_push_images }}"
    build:
      dockerfile: Dockerfile.base
      path: "{{ params.pictures_processor.localdir | default(geokrety_base_dir+'/git/pictures-processor') }}"
      pull: "{{ geokrety_push_images }}"

- name: "'{{ item }}' - Build and push PICTURES PROCESSOR DOWNLOADER image - {{ params.pictures_processor.localdir | default(geokrety_base_dir+'/git/pictures-processor') }} | {{ geokrety_docker_image_pictures_processor_downloader_image_name }}:{{ item }}"
  docker_image:
    name: "{{ geokrety_docker_image_pictures_processor_downloader_image_name }}:{{ item }}"
    source: build
    force_source: yes
    push: "{{ geokrety_push_images }}"
    build:
      dockerfile: Dockerfile.downloader
      path: "{{ params.pictures_processor.localdir | default(geokrety_base_dir+'/git/pictures-processor') }}"
      pull: "{{ geokrety_push_images }}"
      args:
        BASE_IMAGE: "{{ geokrety_docker_image_pictures_processor_base_image_name }}"
        BASE_TAG: "{{ item }}"

- name: "'{{ item }}' - Build and push PICTURES PROCESSOR UPLOADER image - {{ params.pictures_processor.localdir | default(geokrety_base_dir+'/git/pictures-processor') }} | {{ geokrety_docker_image_pictures_processor_uploader_image_name }}:{{ item }}"
  docker_image:
    name: "{{ geokrety_docker_image_pictures_processor_uploader_image_name }}:{{ item }}"
    source: build
    force_source: yes
    push: "{{ geokrety_push_images }}"
    build:
      dockerfile: Dockerfile.uploader
      path: "{{ params.pictures_processor.localdir | default(geokrety_base_dir+'/git/pictures-processor') }}"
      pull: "{{ geokrety_push_images }}"
      args:
        BASE_IMAGE: "{{ geokrety_docker_image_pictures_processor_base_image_name }}"
        BASE_TAG: "{{ item }}"
