---

- name: "'{{ item }}' Define POSTGRES image name"
  set_fact:
    geokrety_docker_image_postgres_image_name: "{{ ('local/' if params.postgres.localdir is defined else '') + geokrety_docker_image_postgres_image }}"

- name: "'{{ item }}' Define POSTGRES image tag"
  set_fact:
    geokrety_docker_image_postgres_image_tag: "{{ 'devel' if params.postgres.localdir is defined else (params.postgres.docker_tag | default(geokrety_postgres_image.docker_tag) | replace('/','-')) }}"


- name: "'{{ item }}' - Build POSTGRES image - {{ params.postgres.localdir }} | {{ geokrety_docker_image_postgres_image_name }}:{{ geokrety_docker_image_postgres_image_tag }}"
  docker_image:
    name: "{{ geokrety_docker_image_postgres_image_name }}:{{ geokrety_docker_image_postgres_image_tag }}"
    source: build
    force_source: yes
    push: no
    build:
      dockerfile: Dockerfile
      path: "{{ params.postgres.localdir }}"
      pull: yes
  when: params.postgres.localdir is defined
