---

- name: "'{{ item }}' Define BASEX AMQP SYNC image name"
  set_fact:
    geokrety_docker_image_basex_amqp_sync_image_name: "{{ ('local/' if params.basex_amqp_sync.localdir is defined else '') + geokrety_docker_image_basex_amqp_sync_image }}"

- name: "'{{ item }}' Define BASEX AMQP SYNC image tag"
  set_fact:
    geokrety_docker_image_basex_amqp_sync_image_tag: "{{ 'devel' if params.basex_amqp_sync.localdir is defined else (params.basex_amqp_sync.docker_tag | default(geokrety_basex_amqp_sync_image.docker_tag) | replace('/','-')) }}"


- name: "'{{ item }}' - Build BASEX AMQP SYNC image - {{ params.basex_amqp_sync.localdir }} | {{ geokrety_docker_image_basex_amqp_sync_image_name }}:{{ geokrety_docker_image_basex_amqp_sync_image_tag }}"
  docker_image:
    name: "{{ geokrety_docker_image_basex_amqp_sync_image_name }}:{{ geokrety_docker_image_basex_amqp_sync_image_tag }}"
    source: build
    force_source: yes
    push: no
    build:
      dockerfile: Dockerfile
      path: "{{ params.basex_amqp_sync.localdir }}"
      pull: yes
  when: params.basex_amqp_sync.localdir is defined
