---

- name: "'{{ item }}' - Generate docker-compose file"
  template:
    src: geokrety_legacy.yml
    dest: "{{ geokrety_base_dir }}/geokrety_legacy.yml"
    owner: "{{ geokrety_username }}"
    group: "{{ geokrety_group }}"
    mode: 0640

- name: "'{{ item }}' - Deploy stack - {{ geokrety_base_dir }}/geokrety_legacy.yml"
  docker_stack:
    state: present
    name: "{{ geokrety_docker_stack_base_name }}-{{ item }}"
    resolve_image: always
    prune: true
    with_registry_auth: true
    compose:
      - "{{ geokrety_base_dir }}/geokrety_legacy.yml"

## Services don't update by themself if image is already present locally (ie: in dev)
## https://github.com/moby/moby/issues/31357
## One option is to force services to be updated
## Find service with need update by looking at the image field in
## $ docker ps |grep geokrety-legacy-new-theme_
## and issue the update command for each of non up to date service
## $ docker service update --force geokrety-new-theme_postgres
