---

- name: "'{{ item }}' - Generate docker-compose file"
  template:
    src: geokrety_legacy.yml
    dest: "{{ geokrety_base_dir }}/geokrety_legacy.yml"
    owner: "{{ geokrety_username }}"
    group: "{{ geokrety_group }}"
    mode: 0640

- name: "'{{ item }}' - Deploy stack"
  docker_stack:
    state: present
    name: "{{ geokrety_docker_stack_base_name }}-{{ item }}"
    resolve_image: "{{ 'always' if geokrety_push_images|bool else 'never' }}"
    compose:
      - "{{ geokrety_base_dir }}/geokrety_legacy.yml"
