---

- name: "{{ item }} - Define params for instance"
  set_fact:
    params: '{{ geokrety_environments | selectattr("name", "equalto", item) | list | first }}'

- name: "{{ item }} - Checkout cdn code"
  git:
    repo: https://github.com/geokrety/GeoKrety-Static.git
    dest: "{{ geokrety_home }}/www/cdn-{{ item }}"
    separate_git_dir: "{{ geokrety_home }}/www/cdn-{{ item }}.git"
    version: "{{ params.geokrety_cdn_git_branch | default(geokrety_cdn_git_branch) }}"
    force: yes
  become_user: "{{ geokrety_username }}"

- block:
  - name: "{{ item }} - Create user AUFS data directory"
    file:
      path: "{{ geokrety_data_dir_base }}-{{ item }}"
      state: directory
      owner: www-data
      group: www-data
      mode: 0755

  - name: "{{ item }} - Create user AUFS mount directory"
    file:
      path: "{{ geokrety_data_dir_base }}-{{ item }}-aufs"
      state: directory
      owner: www-data
      group: www-data
      mode: 0755

  - name: "{{ item }} - Mount AUFS"
    mount:
      path: "{{ geokrety_data_dir_base }}-{{ item }}-aufs"
      src: none
      fstype: aufs
      opts: "br={{ geokrety_data_dir_base }}-{{ item }}:{{ geokrety_data_dir_base }}-prod"
      state: mounted

  when: "item != 'prod'"

- name: "{{ item }} - Deploy cdn stack"
  docker_stack:
    state: present
    name: geokrety_cdn
    compose:
      - /srv/docker/geokrety_cdn.yml
...
