---

- name: Deploy docker-compose files
  template:
    src: "geokrety_{{ item }}.yml"
    dest: /srv/docker/
    owner: root
    group: root
    mode: 0660
  with_items:
    - polls
    - mole_name
    - srtm
    - cdn
  notify:
    - "deploy {{item}} stack"

...
