---

- include_tasks: preflight.yml

- include_tasks: minisites.yml


- block:
  - name: Filter environments to build using 'extra-variable'
    set_fact:
      environments: "{{ [instance] if instance|default(false) else geokrety_environments | map(attribute='name') | list }}"

  - debug:
      msg: "Will process environment(s): {{ environments | join(', ') }}"

  - name: Process environments
    include_tasks: 00-process.yml
    with_items: "{{ environments }}"

  tags:
    - legacy

...
