---

- name: 'minisites' - Ensure directories present
  file:
    path: "{{ item }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0770
  with_items:
    - "{{ geokrety_home }}/minisites"
    - "{{ geokrety_home }}/minisites/the-mole-name"
    - "{{ geokrety_home }}/minisites/the-mole-name/configs"
    - "{{ geokrety_home }}/minisites/the-mole-name/database"
    - "{{ geokrety_home }}/minisites/the-mole-name/www"

- name: 'minisites' - polls - Checkout landing page
  git:
    repo: https://github.com/geokrety/GeoKrety-Polls-Landing-Page.git
    dest: "{{ geokrety_home }}/minisites/www"/the-mole-name"
    separate_git_dir: "{{ geokrety_home }}/minisites/www"/the-mole-name.git"
    force: yes
  become_user: "{{ geokrety_username }}"
  notify:
    - deploy polls stack

- name: 'minisites' - mole-name - Deploy config
  template:
    src: "mole_name_config.conf.j2"
    dest: "{{ geokrety_home }}/minisites/the-mole-name/configs/custom.conf"
    owner: "{{ geokrety_username }}"
    group: "{{ geokrety_group }}"
    mode: 0440
  notify:
    - deploy mole_name stack

- name: 'minisites' - Deploy docker-compose files
  template:
    src: "geokrety_{{ item }}.yml"
    dest: /srv/docker/
    owner: root
    group: root
    mode: 0660
  with_items:
    - mole_name
    - polls
    - srtm
  notify:
    - "deploy {{item}} stack"

...
