---

- name: Install admin ssh keys
  authorized_key:
    user: "{{ geokrety_username }}"
    state: present
    key: "{{ lookup('file', 'pubkeys/' + item) }}"
  with_items: "{{ geokrety_admin_ssh_keys }}"

- name: Install useful python libraries
  pip:
    executable: /usr/bin/pip3
    name:
      - jsondiff
      - ansible==2.8.0rc2
      - sh

...
