---
# vim:set ts=2 sw=2 ai et bg=dark:
version: '3.7'
services:

  service:
    image: kumy/srtm-server:latest
    volumes:
      # TODO move to another dir like data
      - "{{ geokrety_home }}/www/srtm-data:/root/.cache/srtm"
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: "traefik_default"
        traefik.frontend.rule: "Host:geo.geokrety.org,geo.kumy.org"
        traefik.frontend.passHostHeader: "true"
        traefik.protocol: "http"
        traefik.port: 5000
        # traefik2
        traefik.http.routers.geokrety-geo.rule: "Host(`geo.geokrety.org`) || Host(`geo.kumy.org`)"
        traefik.http.routers.geokrety-geo.priority: 5
        traefik.http.routers.geokrety-geo.middlewares: "X-Forwarded-Https@file"
        traefik.http.services.geokrety-geo.loadbalancer.passhostheader: "true"
        traefik.http.services.geokrety-geo.loadbalancer.server.port: 5000
      restart_policy:
        condition: any
    networks:
      default:
      traefik_default:

  zip:
    image: nginx
    volumes:
      - "{{ geokrety_home }}/databases/srtm/:/usr/share/nginx/html/"
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: "traefik_default"
        traefik.frontend.rule: "Host:srtm.geokrety.org"
        traefik.frontend.passHostHeader: "true"
        # traefik2
        traefik.http.routers.geokrety-srtm.rule: "Host(`srtm.geokrety.org`)"
        traefik.http.routers.geokrety-srtm.priority: 5
        traefik.http.routers.geokrety-srtm.middlewares: "X-Forwarded-Https@file"
        traefik.http.services.geokrety-srtm.loadbalancer.passhostheader: "true"
        traefik.http.services.geokrety-srtm.loadbalancer.server.port: 80
      restart_policy:
        condition: any
    networks:
      traefik_default:

networks:
  default:
  traefik_default:
    external: true
