---
version: '3.7'

services:

  service:
    image: geokrety/the-mole-name:latest
    volumes:
      - "{{ geokrety_home }}/minisites/the-mole-name/database/the-mole-name:/opt/flask/database:rw"
      - "{{ geokrety_home }}/minisites/the-mole-name/configs/the-mole-name:/opt/flask/config:rw"
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: "traefik_default"
        traefik.frontend.rule: "Host:polls.geokrety.org; PathPrefix:/molename"
        traefik.frontend.passHostHeader: "true"
        traefik.protocol: "http"
        traefik.port: 8000
        # traefik2
        traefik.http.routers.geokrety-polls-the-mole-name.rule: "Host(`polls.geokrety.org`) && PathPrefix(`/molename`)"
        traefik.http.routers.geokrety-polls-the-mole-name.priority: 10
        traefik.http.routers.geokrety-polls-the-mole-name.middlewares: "X-Forwarded-Https@file"
        traefik.http.services.geokrety-polls-the-mole-name.loadbalancer.passhostheader: "true"
        traefik.http.services.geokrety-polls-the-mole-name.loadbalancer.server.port: 8000
      restart_policy:
        condition: any
    networks:
      default:
      traefik_default:

networks:
  default:
  traefik_default:
    external: true
